Add support for storing list of associations
AY2425S1-CS2103-F13-2/tp pull request #106
Opened 2024-10-17 06:56 UTC by kevin-pek

Resolves #96 and #97.

- Added support for deserializing and validating associations in JSON files.
- Enhanced logic and validation for unique lists for vendors, events, and associations to prevent duplicates based on `UniqueId`.
- Fixed NullPointerException in tests related to invalid or missing association data.

2024-10-23 09:03 UTC, hanscau requested changes
Might need to save UniqueId in the model of vendor and event, if not there is no way to track which UniqueId belongs to which model after the app is open and closed again, resetting the hashMap inside the respective models

2024-10-23 09:03 UTC, hanscau commented on src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
>              addressBook.addEvent(event);
This will create an event with a uniqueId that is different from the one that is already specified in the save file

2024-10-23 09:03 UTC, hanscau commented on src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
>              addressBook.addVendor(vendor);
This will create a vendor with a uniqueId that is different from the one that is already specified in the save file

2024-10-23 12:39 UTC, kevin-pek commented on src/main/java/seedu/address/ui/MainWindow.java
When deciding to change this, I was also thinking that we would also need to use the logic to get the list of associated vendors and the list of remaining vendors within the details panels. Or is that something that can be avoided altogether?

2024-10-23 13:07 UTC, hanscau commented on src/main/java/seedu/address/ui/MainWindow.java
One way is to maintain a list of associated vendor and remaining vendor on the model side, then that list is just passed to the UI. Alternatively is to have a util method that can do the filtering, so the logic does not need to reside on the details page

2024-10-24 13:52 UTC, kevin-pek commented on src/main/java/seedu/address/ui/MainWindow.java
For now, I have implemented this feature by passing in the logic instance to make updating the current event/vendors' associated vendors simpler. Worth revisiting this again next milestone to see how this can be better done.

2024-10-29 11:39 UTC, Jasperabez requested changes
- Minor cosmetic/documentation changes required
- Instead of deleting EditCommandTest.java it should be replaced by the latest copy on master. (deleting would essentially remove it from master too once merged)
- Flag codecov seems to be minor but would be good to add test too if time allows

2024-10-29 11:39 UTC, Jasperabez commented on src/main/java/seedu/address/model/AddressBook.java
> +     * {@code vendor} and {@code event} must exist in the respective lists.
respective lists could be more verbose quite unclear and vague as of now

2024-10-29 11:39 UTC, Jasperabez commented on src/main/java/seedu/address/model/AddressBook.java
> +     * {@code vendor} and {@code event} must exist in their respective lists.
same issue

2024-10-29 13:11 UTC, C5hives commented on src/main/java/seedu/address/model/AddressBook.java
> +     * {@code vendor} and {@code event} must exist in the respective lists.
I think the javadoc could just be kept as "address book".

The internal implementation details of the event and vendor lists don't need to be exposed by specifying that two lists exist in the address book. Also less finnicky to phrase!

2024-10-29 14:05 UTC, C5hives commented on src/main/java/seedu/address/model/vendor/Vendor.java
Same question as the one in `Event`. You updated `hashCode()` to include `UniqueId`, but didn't for `equals()`.

Not sure if intentional.

2024-10-29 14:11 UTC, C5hives commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> +    private final Map<UniqueId, Event> eventMap = new HashMap<>();
Same (possible) issue as `UniqueVendorList`

2024-10-29 14:17 UTC, C5hives commented on src/test/java/seedu/address/logic/commands/EditCommandTest.java
As mentioned by Jabez, this file deletion should be reverted.

2024-10-30 02:08 UTC, kevin-pek commented on src/main/java/seedu/address/model/vendor/UniqueVendorList.java
> +    private final Map<UniqueId, Vendor> vendorMap = new HashMap<>();
I think the suggestion to use `LinkedHashMap` makes the most sense for this, since the reason for the `Map` was to avoid iterating through the entire list to get a specific entry.

2024-10-30 02:31 UTC, kevin-pek commented on src/main/java/seedu/address/model/event/Event.java
`hashCode` was edited to factor in the id in order to make sure that items with different id values will be treated differently in their UniqueList classes.

However changing the `equals` method conflicts with how we are testing the command parsing logic. For example, the command parsing tests for `CreateVendorCommand` and `EditVendorCommand` will fail because of how a vendor with a different id will be created when it parses the arguments. Maybe a separate issue should be made to refactor all of this?

2024-10-30 05:30 UTC, Jasperabez commented on src/main/java/seedu/address/model/event/Event.java
I am in it for refactoring it in a separate issue

2024-10-30 06:49 UTC, Jasperabez commented on src/main/java/seedu/address/ui/MainWindow.java
#144 created to address this

2024-10-30 06:50 UTC, Jasperabez commented on src/main/java/seedu/address/model/event/Event.java
#143 created to resolve this

2024-10-30 06:50 UTC, Jasperabez commented on src/main/java/seedu/address/model/vendor/UniqueVendorList.java
> +    private final Map<UniqueId, Vendor> vendorMap = new HashMap<>();
#142 created to resolve this

2024-10-30 06:52 UTC, Jasperabez approved these changes
LGTM also did a quick sanity check to check whether assignment works and preserves across app runs.

2024-10-30 07:01 UTC, merged