Update Find Command from AB3
AY2425S1-CS2103-F13-2/tp pull request #121
Opened 2024-10-22 15:47 UTC by Jasperabez

Closes: #117

- Implemented FindEventCommand and FindVendorCommand
- Updated FindCommandParser
- Added Tests

Note: 
potential duplication in predicate model, to be addressed in #79
can explore filtering both event and vendor simultaneously since keywords are currently tagged to their prefix
E.g: `find v/ abel e/ birthday` abel is keyword for vendor list and etc.

2024-10-23 09:19 UTC, hanscau requested changes
Seems like it can only filter for exact keywords, search for "a" won't return "Saturday".
Find also only look at names, searching for dates and phone number doesn't work. Should we modify it work for those either?

On a separate note, I find it very annoying when my search turns up to be nothing and I have to `list e/` to view the list of events again. Maybe default behavior for no search found is to filter nothing? So the entire list is still visible

2024-10-23 09:19 UTC, hanscau commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example to find an event: " + COMMAND_WORD + " " + PREFIX_EVENT + " party birthday banquet\n";
Should it be:
"Parameter: " + COMMAND_WORD + " <" + PREFIX_VENDOR + " OR " + PREFIX_EVENT + ">" + " KEYWORD [MORE_KEYWORDS]..."

and 

"Example: " + COMMAND_WORD + " <" + PREFIX_VENDOR + " OR " + PREFIX_EVENT + ">" + "birthdays\n";

To be consistent with the MESSAGE_USAGE for delete and view

2024-10-23 13:08 UTC, hanscau commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example to find an event: " + COMMAND_WORD + " " + PREFIX_EVENT + " party birthday banquet\n";
So all the commands that can be used for e/ and v/ will have 2 examples instead? rather than the <e/ or v> format?

2024-10-23 13:10 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example to find an event: " + COMMAND_WORD + " " + PREFIX_EVENT + " party birthday banquet\n";
I would prefer to keep the prefixes separated too. It's understandable if `<v/ or e/>` is used, but separating them visually might help to signal to the user that the `v/` and `e/` prefixes are mutually exclusive.

2024-10-23 13:13 UTC, C5hives commented
> On a separate note, I find it very annoying when my search turns up to be nothing and I have to `list e/` to view the list of events again. Maybe default behavior for no search found is to filter nothing? So the entire list is still visible

Suggestion Only: Would it be feasible to display a failure message in the console when nothing is found? Then the original unfiltered list can be displayed.

The current method of displaying the results is more intuitive but might be more clunky if the user plans to go fast.
If the entire list is still visible, the user might misunderstand it as "results were found". The console message might not be enough to notify the user.

2024-10-23 18:02 UTC, Jasperabez commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example to find an event: " + COMMAND_WORD + " " + PREFIX_EVENT + " party birthday banquet\n";
I've created a new issue for standardizing multi prefixes naming in parent abstract class #124 if @hanscau agree with this approach

2024-10-23 18:16 UTC, Jasperabez commented
> Seems like it can only filter for exact keywords, search for "a" won't return "Saturday". Find also only look at names, searching for dates and phone number doesn't work. Should we modify it work for those either?

@hanscau would change the filter implementation, but caveat is that <space> would not be counted as part of the keyword as <space> is used as a delimiter for keywords. (So not exactly what you think is Ctrl F). I would prefer if extending searching for dates and phone number is done in a separate PR, after I done #79.

> On a separate note, I find it very annoying when my search turns up to be nothing and I have to `list e/` to view the list of events again. Maybe default behavior for no search found is to filter nothing? So the entire list is still visible

Since this is the consensus I would switch to this as the implementation.

2024-10-23 19:34 UTC, Jasperabez commented
@hanscau partial keyword matching and error message implemented

If #124 resolves the naming and 
ok to work on finding in date and phone number as a separate issue 
I think we can resolve the conversation and ready to merge after review

2024-10-24 13:59 UTC, C5hives requested changes
See suggestions!

2024-10-24 13:59 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/util/PredicateDryRunUtil.java
Would really prefer to not use "Dry Run" to describe this class (and its methods).

Try "preview" instead?

2024-10-24 13:59 UTC, C5hives commented on src/main/java/seedu/address/logic/parser/FindCommandParser.java
> +            }
Would it be better to let `processKeywords` throw the `ParseException` immediately instead of doing a length check afterwards?

This feels slightly redundant.

2024-10-24 15:11 UTC, C5hives approved these changes
Looks good!

2024-10-24 15:17 UTC, merged