Revamp unassign from view mode for nested eventvendor list
AY2425S1-CS2103-F13-2/tp pull request #151
Opened 2024-10-30 19:27 UTC by Jasperabez

- Unassign in view mode now only looks at assigned events/vendors
- Assigned events/vendors now don't show up on assignable list

2024-11-03 05:58 UTC, C5hives requested changes
Gave some suggestions. Not sure if `UnassignCommand` is getting too large and needs to be broken up.

2024-11-03 05:58 UTC, C5hives commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +        }
I hate how coupled our UI is to our actual logic, but I also don't see a way around this.

2024-11-03 05:58 UTC, C5hives commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
I think ignoring the vendor prefix entirely would make more sense. Just take the vendor to unassign from `model.getViewedVendor().getValue()` (line 92) directly.

2024-11-03 05:58 UTC, C5hives commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Similar to previous

2024-11-03 05:58 UTC, C5hives commented on src/main/java/seedu/eventtory/model/ModelManager.java
> +    private Predicate<Vendor> getVendorPredicateForUiState() {
can omit `ForUiState`. Maybe consider `evaluateVendorPredicate` instead?

2024-11-03 05:58 UTC, C5hives commented on src/main/java/seedu/eventtory/model/util/PredicateBuilder.java
> +    }
Worth testing?

2024-11-03 05:58 UTC, C5hives commented on src/test/java/seedu/eventtory/logic/commands/UnassignCommandTest.java
> +        model.viewVendor(vendor); // Sets UiState to VENDOR_DETAILS
Misleading comment? The next line is the one actually setting the `UiState` to `VENDOR_DETAILS`.

Did you mean: "Simulate user viewing a vendor" instead?

2024-11-03 05:58 UTC, C5hives commented on src/test/java/seedu/eventtory/logic/commands/UnassignCommandTest.java
> +        model.viewEvent(event); // Sets UiState to EVENT_DETAILS
Same issue as other comment

2024-11-03 11:03 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
should be resolved by #159

2024-11-03 19:36 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
sike actually not gonna be resolved, the main issue with this is the unassign command is not "deterministic". 
Like `assign v/10 e/3` and `assign v/1000 e/3` would essentially do the same thing, this would be solved if we have a index for the current item displayed with the item (best solution IMO).

The other solution is to have unassign only to be done in view mode so depending on the current view. `unassign idx` without the prefix.

But too much of a pain to implement... so overall cooked.

2024-11-03 19:47 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +        }
I do too.... this is so cooked

2024-11-03 19:48 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Alternative just say this is the desired behaviour in the user docs? Which is quite wild not gonna lie

2024-11-04 09:04 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Gonna make change unassign and assign to view mode only

2024-11-04 09:04 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
@C5hives please approve #159

2024-11-04 13:01 UTC, kevin-pek commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Think the first idea suggested would make the most sense? Just fixing the current vendor/event to be at index 1.

2024-11-04 13:09 UTC, kevin-pek commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Maybe for the `Assign` and `Unassign` commands, when the view is in either detail view, we enforce the vendor or event index to be 1 for the command to be valid, but we follow what @C5hives suggested to get the currently viewed vendor or event?

2024-11-04 18:11 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/UnassignCommand.java
> +            return handleMainView(model);
Let's change unassign and assign to be only usable in view mode to save us some headache

2024-11-05 07:08 UTC, merged