Allow find command to search through all fields
AY2425S1-CS2103-F13-2/tp pull request #156
Opened 2024-11-02 04:13 UTC by kahsuann

Event's EventNameContainsKeywordsPredicate -> EventContainsKeywordsPredicate
Vendor's NameContainsKeywordsPredicate -> VendorContainsKeywordsPredicate

2024-11-02 10:29 UTC, Jasperabez approved these changes
LGTM! did some functionality testing on my own and the test cases seems to be well covered

2024-11-03 05:22 UTC, C5hives requested changes
Just one naming issue that was missed previously!

2024-11-03 05:22 UTC, C5hives commented on src/main/java/seedu/eventtory/logic/commands/util/PredicatePreviewUtil.java
>      public static FilteredList<Vendor> getPreviewofFilteredVendors(Model model,
Oops, camelCase issue here that was likely missed. Should be `getPreviewOfFilteredVendors` (with a capital 'O' in 'Of').

2024-11-03 05:22 UTC, C5hives commented on src/main/java/seedu/eventtory/logic/commands/util/PredicatePreviewUtil.java
>      public static FilteredList<Event> getPreviewofFilteredEvents(Model model,
Same as previous.

2024-11-03 14:15 UTC, C5hives approved these changes

2024-11-03 14:15 UTC, merged