Add trailing indexing scheme in view mode
AY2425S1-CS2103-F13-2/tp pull request #159
Opened 2024-11-02 17:52 UTC by Jasperabez

Assigned events/vendors now have their index starting +1 from the last number in assignable.
As such there should be no more ambiguity which index is being referred to in the user's input command.

Added a `IndexResolverUtil` that takes in vendor, event index and return a vendor, model based on the current UI display state (changes the trailing to a proper idx pointing to assigned). 
The util class also does checks and throw exception if index is out of bounds

Resolves: #149

2024-11-02 21:21 UTC, Jasperabez commented
the last 2 percent was too painful Im out of ideas

2024-11-03 05:16 UTC, C5hives requested changes
I like the extracting of list index resolution into a centralized class.
There are a few issues I have with some of the naming. Let me know if they make sense.

2024-11-03 05:16 UTC, C5hives commented on src/main/java/seedu/eventtory/ui/EventListPanel.java
> +        private final ObservableIntegerValue displayIndexOffset;
Consider renaming this to simply `indexOffset` or `eventIndexOffset`. The word `display` doesn't add much value here.

2024-11-03 05:16 UTC, C5hives commented on src/main/java/seedu/eventtory/ui/VendorDetailsPanel.java
> +        displayAssignedStartIndex = logic.getAssignedEventsDisplayStartIdx();
`displayAssignedStartIndex` sounds exactly like a function/method name. Variable names should not start with a verb,

Consider renaming to `startIndexOfAssignedEvents` instead.

2024-11-03 05:16 UTC, C5hives commented on src/main/java/seedu/eventtory/ui/VendorListPanel.java
> +        ObservableIntegerValue displayIndexOffset) {
Same issue here. Consider renaming to `indexOffset` or `vendorIndexOffset`.

2024-11-03 05:16 UTC, C5hives commented on src/test/java/seedu/eventtory/logic/commands/AssignCommandTest.java
> +
Nice catch for better code coverage!

2024-11-03 05:16 UTC, C5hives commented on src/test/java/seedu/eventtory/testutil/EventBuilder.java
> +        tags = new HashSet<>(eventToCopy.getTags());
Seems redundant. `eventToCopy.getTags()` already returns a `Set`, which can be directly assigned to `tags`.

Was this causing an issue and thus needed to be changed?

2024-11-03 10:58 UTC, Jasperabez commented on src/test/java/seedu/eventtory/testutil/EventBuilder.java
> +        tags = new HashSet<>(eventToCopy.getTags());
Trying to match up the implementation between VendorBuilder and EventBuilder

2024-11-03 10:59 UTC, Jasperabez commented on src/main/java/seedu/eventtory/logic/commands/util/IndexResolverUtil.java
> +        String errorMessage) throws CommandException {
Good idea!

2024-11-03 13:36 UTC, C5hives commented on src/test/java/seedu/eventtory/testutil/EventBuilder.java
> +        tags = new HashSet<>(eventToCopy.getTags());
I'd say change `VendorBuilder` to match this implementation, instead of the other way round.

2024-11-03 15:01 UTC, kevin-pek commented on src/test/java/seedu/eventtory/testutil/EventBuilder.java
> +        tags = new HashSet<>(eventToCopy.getTags());
Agree, makes more sense to modify `VendorBuilder` than the other way around.

2024-11-04 12:58 UTC, C5hives requested changes
Just one more small change to naming. The rest looks good!

2024-11-04 12:58 UTC, C5hives commented on src/main/java/seedu/eventtory/model/ModelManager.java
> +    private final ObservableIntegerValue startingIndexOfAssignedEvents;
Should be changed to `startIndexOfAssigned...` instead of `starting` for consistency with naming in other files.

2024-11-04 12:58 UTC, C5hives commented on src/main/java/seedu/eventtory/model/ModelManager.java
> +    public ObservableIntegerValue getStartingIndexOfAssignedVendors() {
Same for these methods.

2024-11-04 12:58 UTC, C5hives commented on src/main/java/seedu/eventtory/model/ModelManager.java
> +    private final ObservableIntegerValue startingIndexOfAssignedEvents;
Alternatively, change all similar variables to `startingIndex...`

2024-11-04 14:09 UTC, C5hives approved these changes

2024-11-04 14:09 UTC, merged