Improve UML diagrams and developer documentation
AY2425S1-CS2103-F13-2/tp pull request #336
Opened 2024-11-10 15:26 UTC by kevin-pek

Resolves #324.

Changes made:
- Remove UiPart class from `UiClassDiagram.puml`
- Split sequence diagram from `AssignSequenceDiagram.puml` into 2 separate diagrams and updated DG for better clarity.
- Removed fields from `ModelClassDiagram.puml`.
- Removed `BetterModelClassDiagraml.puml` since it is no longer used.
- Removed irrelevant labels from dependency relationships in `LogicClassDiagram.puml`.

2024-11-10 15:34 UTC, Jasperabez commented
Diagrams:
![UiClassDiagram](https://github.com/user-attachments/assets/d1469e27-19e7-4564-83d0-be56456746a7)
![AssignParserSequenceDiagram](https://github.com/user-attachments/assets/a7dd948c-7ff6-4ef3-a697-fdbb8c1f32bc)
![AssignSequenceDiagram](https://github.com/user-attachments/assets/d5e2d0a3-2d16-42e4-a20f-f4a9a2638b4f)
![ModelClassDiagram](https://github.com/user-attachments/assets/50ddfbc7-e412-49b5-81d8-5324f9a4242a)
![LogicClassDiagram](https://github.com/user-attachments/assets/fd7a9dfb-a3c4-49c4-8b01-62704a9d6c7c)

2024-11-10 15:36 UTC, kevin-pek commented
Am thinking if its a good idea to replace with the conditional flow of the assign command to just show the `AssignCommand` calling its own `assignEventToVendor(m)` method? Sequence diagram might still be too complicated.

2024-11-10 15:36 UTC, Jasperabez commented
@kevin-pek looks correct but maybe the line to the right of `EventDetailsPanel` in the UI diagram could be adjusted to the left if possible.

Would prob get @C5hives to double check the diagrams and approve too.

2024-11-10 15:50 UTC, C5hives commented
For the `Model` class diagram, should the multiplicities for `Vendor` i.e. `* filtered` and `* all` be swapped? I think the current notation is incorrect.

2024-11-10 15:51 UTC, C5hives commented
Also, I think keeping the labels `creates`, etc. helps a lot with the readability of the `Logic` class diagram.

Maybe consider re-adding them and just remove the `<<>>` brackets?

2024-11-10 15:56 UTC, C5hives commented on docs/DeveloperGuide.md
>  The UI consists of a `MainWindow` that is made up of parts e.g.`CommandBox`, `ResultDisplay`, `PersonListPanel`, `StatusBarFooter` etc. All these, including the `MainWindow`, inherit from the abstrac
Do you want to explain that the inheritance from `UiPart` was intentionally left out in the class diagram to reduce clutter?

2024-11-10 16:06 UTC, kevin-pek commented
![Screenshot 2024-11-11 at 12 06 24 AM](https://github.com/user-attachments/assets/ebae3407-e050-4e92-b13f-55d9c5a50b40)

Have simplified the sequence diagram to this, thoughts?

2024-11-10 16:11 UTC, C5hives commented
> ![Screenshot 2024-11-11 at 12 06 24 AM](https://github.com/user-attachments/assets/ebae3407-e050-4e92-b13f-55d9c5a50b40)
> 
> Have simplified the sequence diagram to this, thoughts?

The entire alt block is jutting out quite a bit on the left. I assume this is PlantUml's doing again?

2024-11-10 16:20 UTC, kevin-pek commented
> > ![Screenshot 2024-11-11 at 12 06 24 AM](https://private-user-images.githubusercontent.com/76090938/384704838-ebae3407-e050-4e92-b13f-55d9c5a50b40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTUzOTcsIm5iZiI6MTczMTI1NTA5NywicGF0aCI6Ii83NjA5MDkzOC8zODQ3MDQ4MzgtZWJhZTM0MDctZTA1MC00ZTkyLWIxM2YtNTVkOWM1YTUwYjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE2MTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDNhZjRmNGM2ODI2MjZiYjE1ZjkwNTdkNTA4NzVkMzg5OGRkZDdhOGE2MDg4NjIxMmUxZjc2ZmZhZjgzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G345uPxUo4jzDAceGhb1x8macMt9VcJboRiMCGm6sDw)
> > Have simplified the sequence diagram to this, thoughts?
> 
> The entire alt block is jutting out quite a bit on the left. I assume this is PlantUml's doing again?
> 
> But it definitely looks better. I think this is the way to go

Issue is caused by the CommandException being thrown in the else case, not too sure how to better present this. 🤔

2024-11-10 16:23 UTC, kevin-pek commented
> For the `Model` class diagram, should the multiplicities for `Vendor` i.e. `* filtered` and `* all` be swapped? I think the current notation is incorrect.

I believe the multiplicity should be correct? A single `UniqueList` or `ModelManager` should contain zero or more `Vendor` objects and so on.

2024-11-10 16:26 UTC, kevin-pek commented
> Also, I think keeping the labels `creates`, etc. helps a lot with the readability of the `Logic` class diagram.
> 
> Maybe consider re-adding them and just remove the `<<>>` brackets?
> 
> Another thing we missed: For the `Logic` class diagram, the note for `XYZCommand` is technically wrong as we no longer have an `AddCommand`. Should be `CreateVendorCommand` or `CreateEventCommand`, or can be another command entirely.

Was thinking about this, but couldn't find examples in the textbook where dependency relationships (dotted arrows) included labels, so decided to remove them.

2024-11-11 06:46 UTC, C5hives commented
> > For the `Model` class diagram, should the multiplicities for `Vendor` i.e. `* filtered` and `* all` be swapped? I think the current notation is incorrect.
> 
> I believe the multiplicity should be correct? A single `UniqueList` or `ModelManager` should contain zero or more `Vendor` objects and so on.

Error on my part. Was referring to the association roles (`filtered` vs. `all`).
![image](https://github.com/user-attachments/assets/fd013311-250a-4de9-b068-9e2f6d43bf66)

Since `ModelManager` only holds on to a filtered `Vendor` list, the association roles in the current diagram would be wrong. (see how the roles are flipped for `Vendor` compared to `Event`)
![image](https://github.com/user-attachments/assets/0b908438-4d94-4520-826e-146193c219d3)

Again, I think this is an issue with how PlantUml renders the association labels. The notation is correct in text form, but overlaps and causes confusion when rendered.
![image](https://github.com/user-attachments/assets/980ed088-f3bb-4ad0-9d43-7dea243ac8d1)

2024-11-11 06:48 UTC, C5hives commented on docs/diagrams/AssignSequenceDiagram.puml
I think this is serviceable. @AY2425S1-CS2103-F13-2/developers might want to chime in for this.

2024-11-11 06:54 UTC, C5hives commented on docs/DeveloperGuide.md
> +**Note** The classes representing the fields of the models `Vendor`, `Event` and `Association` were not included to reduce the clutter of the diagram.
Consider rephrasing to:

"To reduce visual clutter, auxiliary classes within the `Vendor`, `Event` and `Association` classes have been omitted from the diagram."

2024-11-11 07:00 UTC, C5hives commented
> > Also, I think keeping the labels `creates`, etc. helps a lot with the readability of the `Logic` class diagram.
> > Maybe consider re-adding them and just remove the `<<>>` brackets?
> > Another thing we missed: For the `Logic` class diagram, the note for `XYZCommand` is technically wrong as we no longer have an `AddCommand`. Should be `CreateVendorCommand` or `CreateEventCommand`, or can be another command entirely.
> 
> Was thinking about this, but couldn't find examples in the textbook where dependency relationships (dotted arrows) included labels, so decided to remove them to play it safe. Not sure if this is the right call, though?

I've tried cross-referencing other groups in our tutorial slot but they have all left the diagram untouched. I'm not sure whether omitting the labels is a good idea. @AY2425S1-CS2103-F13-2/developers thoughts on this?

2024-11-11 08:06 UTC, kevin-pek commented
> > > Also, I think keeping the labels `creates`, etc. helps a lot with the readability of the `Logic` class diagram.
> > > Maybe consider re-adding them and just remove the `<<>>` brackets?
> > > Another thing we missed: For the `Logic` class diagram, the note for `XYZCommand` is technically wrong as we no longer have an `AddCommand`. Should be `CreateVendorCommand` or `CreateEventCommand`, or can be another command entirely.
> > 
> > 
> > Was thinking about this, but couldn't find examples in the textbook where dependency relationships (dotted arrows) included labels, so decided to remove them to play it safe. Not sure if this is the right call, though?
> 
> I've tried cross-referencing other groups in our tutorial slot but they have all left the diagram untouched. I'm not sure whether omitting the labels is a good idea. @AY2425S1-CS2103-F13-2/developers thoughts on this?

Have reverted the changes for now, maybe we can refer to past year forums to verify this.

2024-11-11 11:02 UTC, Jasperabez commented on docs/diagrams/AssignSequenceDiagram.puml
LGTM!

2024-11-11 11:10 UTC, Jasperabez requested changes
Would be good to standardize the lack of `<<>>` for ParserClasses UML too

2024-11-11 12:27 UTC, C5hives commented
Current state of diagrams. Is this better?

`LogicClassDiagram.puml`: 
![image](https://github.com/user-attachments/assets/d1cd1b29-7080-4090-ab91-155b1ef66bcd)
`ParserClasses.puml`: 
![image](https://github.com/user-attachments/assets/f0c6224d-0d9a-4283-9945-2884a4bd8133)
`ModelClassDiagram.puml`: 
![image](https://github.com/user-attachments/assets/b4e58503-130d-4971-8b34-a2a609ee6e48)

2024-11-11 12:39 UTC, Jasperabez approved these changes
LGTM! Good work guys

2024-11-11 12:42 UTC, merged