Add create event use case (DG)
AY2425S1-CS2103-F13-2/tp pull request #45
Opened 2024-10-02 18:22 UTC by Jasperabez

Replace existing template use case with "create event" use case for EventTory

2024-10-03 11:20 UTC, C5hives commented
Resolves #45

2024-10-03 11:38 UTC, C5hives requested changes
I have provided some suggestions to make the user case more comprehensive. Let me know if they make sense :)

2024-10-03 11:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +      Use case resumes at step 1.
It might make more sense to end the use case here instead of looping back to step 1 of the MSS.

This would be the most straightforward—the user may choose to give up on creating an event after the failure. If need be, the user may choose to retry this use case by providing fresh input.

2024-10-03 11:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +      Use case resumes at step 1.
Same as comment for line 322.

2024-10-03 11:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +2. System validates the input for the event name and date.
It might be better to omit this step as it is not externally visible to the user. The extensions for this step should definitely stay, but can be tagged to step 1 instead.

![image](https://github.com/user-attachments/assets/1d4f5a8e-3e4f-4bad-b9a7-1dc737024c25)

2024-10-03 11:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +1. User requests to create a new event by providing the event name and date in the correct format.
You might want to omit "in the correct format" and move it to an extension. The extension would then handle situations where the command was incorrectly formatted.

By specifying that the event name and date are in the correct format, it might imply that steps 2a and 2b are redundant as:
- correct format
- event name invalid
- date format invalid

appear to contradict each other.

2024-10-03 14:05 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +2. System validates the input for the event name and date.
Noted good catch!

2024-10-03 14:06 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +1. User requests to create a new event by providing the event name and date in the correct format.
makes sense to me applied the fix!

2024-10-04 12:17 UTC, C5hives approved these changes
Looks good!

2024-10-04 12:18 UTC, merged