Update dg user stories
AY2425S1-CS2103-F13-2/tp pull request #52
Opened 2024-10-05 09:49 UTC by kahsuann

Resolves #39

2024-10-05 10:51 UTC, Jasperabez requested changes
Nit:
- Clarification required for some user stories
- Some use cases labeled _Nice to have_ are included while some were not, instead some _Unlikely to have_ are included.

2024-10-05 10:51 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | find a vendor by name and tags                   | choose a suitable fast for a new event                                                         |
typo? what does `suitable fast` means

2024-10-05 10:51 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | assign a vendor to an event                      | check whether arrangesments have already been made for the event                               |
might need to change the **So that I can** portion, doesn't makes sense as of now.

Maybe: verify if arrangements for that aspect of the event have been completed.
@C5hives what do you think?

2024-10-05 10:51 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | set a progress status to an event or vendor      | keep track of completed and uncompleted transactions                                           |
would be good to clarify transactions?
It is days to when event is set to happen (due date)?
or aspect of event covered by vendor out of all aspects/categories need to be covered?
or vendor deliverables done so far?

If multiple should split into different stories, iirc.

I want to might have to be change to reflect that as well

2024-10-05 10:51 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | block vendors                                    | avoid vendors that I had bad experiences with                                                  |
prefer the original terms used in the google sheets:
"address book remains less cluttered but does not forget vendors to avoid"

2024-10-05 10:51 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `*`      | event planner           | view attachments of an event                     | view working files in the same location                                                        |
Do we include Unlikely to haves in the use cases as well? 318 and 319 (working files related) are unlikely to haves in the sheets

2024-10-06 03:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | fast typer              | autocomplete half-typed commands                 | be even faster                                                                                 |
"be even faster" is too vague as a benefit (I know this was drafted by me).

Can consider "reduce the number of keystrokes required per command" as the benefit instead.

2024-10-06 03:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | fast typer              | map commands to (shorter) aliases                | customise commands that I use often into a more convenient phrases                             |
"into a more convenient phrases" is grammatically incorrect.

Consider omitting the "a" to become "into more convenient phrases" instead.

2024-10-06 03:38 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | set a progress status to an event or vendor      | keep track of completed and uncompleted transactions                                           |
Resolving as developer guide has been edited to address this.

2024-10-06 03:44 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | set a progress status to a vendor                | keep track where vendor deliverables have been completed                                       |
Phrasing suggestion—can consider "keep track of completed vendor deliverables" for benefit instead.

2024-10-06 03:44 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | open whatsapp or telegram from the app           | easily contact vendors without 'leaving' the address book                                      |
The feature and benefit of this user story doesn't seem to match. Being able to open Whatsapp or Telegram within the application does not immediately imply sending messages to them.

Can consider "send Whatsapp or Telegram messages from within the app" for the feature instead to match the benefit.

2024-10-06 03:44 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | assign a vendor to an event                      | check whether arrangesments have already been made for the event                               |
Yup, there's a small leap in logic here but I understand the intention. It should just be an issue in phrasing.

Resolving as the developer guide has been updated to address this.

2024-10-06 03:50 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | assign a vendor to an event                      | verify if arrangements for that aspect of the event have been completed                        |
The benefit "verify if arrangements for that aspect of the event have been completed" might be slightly too verbose for this.

Can consider a more straightforward benefit such as "keep track of which vendors have been hired for an event".

2024-10-06 03:50 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | block vendors                                    | avoid vendors that I had bad experiences with                                                  |
Resolving as the developer guide has been edited to address this.

2024-10-06 03:56 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | block vendors                                    | keep the address book remains less cluttered but does not forget vendors to avoid              |
I would argue that this feature should be renamed to "filter vendors by rating" with the benefit "avoid working with less reputable vendors" instead.

The term "block" does not mean much in the context of the application—there is no two-sided interaction within the application. 

As the application is meant to help the event planner, it would make sense to keep this feature for tracking purposes, but it could be renamed to better reflect the intent of this "blocking" functionality.

2024-10-06 03:56 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `*`      | event planner           | view attachments of an event                     | view working files in the same location                                                        |
There isn't a requirement to omit user stories that are "unlikely to have", so this can stay.

However, the developer guide has already been updated to remove these user stories, so this is no longer applicable—resolving to reflect the changes made.

2024-10-06 03:57 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | find a vendor by name and tags                   | choose a suitable vendor fast for a new event                                                  |
Word choice—can consider replacing "fast" with "quickly" instead.

2024-10-06 03:57 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | find a vendor by name and tags                   | choose a suitable fast for a new event                                                         |
Typo has been addressed in later commits.

2024-10-06 04:17 UTC, C5hives requested changes
I have provided some suggestions to make some user stories more concise.

Although not explicitly stated in our Google Sheets document, some important user stories are missing—primarily, CRUD operations for events and vendors:
- Delete events
- Delete vendors

Let me know if you need clarification for some of my suggestions. Some of them might be subjective and can be contested.

_Note: Remember to resolve the conversations after addressing them! It can be difficult to manually compare future commits with previous suggestions._

2024-10-06 04:17 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | add a vendor                                     |                                                                                                |
"add a vendor" might be too similar (and possibly ambiguous) to the next user story of assigning vendors. Perhaps consider phrasing it in a similar way to line 303 to be something like:
- create a new vendor

The benefit might need to be updated as well.

2024-10-06 04:17 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | create a new event with date, time and location  | easily see upcomings events in my schedule                                                     |
Grammar—change "upcomings" to "upcoming" as adjectives do not have plural endings in English.

Also consider:
- use "track" instead of "see" in the benefit
- omit "in my schedule" entirely

The terms "see" and "schedule" might imply some form of calendar visualisation, which is already covered the user story in line 320.

Renaming this might help to make the user story more concise and helps to keep the benefit relevant to the feature described.

2024-10-06 04:17 UTC, C5hives commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | set list of type of vendors I need for a event   | know what manpower or vendor I am missing for the event                                        |
Can consider renaming the feature to "indicate the types of vendors required for an event".

2024-10-06 04:39 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | fast typer              | autocomplete half-typed commands                 | be even faster                                                                                 |
I'll argue that it's ok for user stories benefit to be generic since it's from the user perspective. but we can change it to something more specific too.

2024-10-06 04:43 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | open whatsapp or telegram from the app           | easily contact vendors without 'leaving' the address book                                      |
agree with this but something about it doesn't sit quite right with me... but I don't have a bett r suggestion to what to change the benefit to

2024-10-06 04:47 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* * *`  | event planner           | assign a vendor to an event                      | verify if arrangements for that aspect of the event have been completed                        |
I think the original idea was to have different vendor categories (catering, flowers, etc.) then you can keep track of the category/aspect that have been satisfied by a vendor of that type. 

however that might be too ambitious in hindsight I think Bo Chang proposed change would be good

2024-10-06 10:05 UTC, Jasperabez requested changes
show be fine after addressing the suggested changes. Do mark them as resolved when addressed :)

2024-10-06 11:20 UTC, Jasperabez requested changes
Some suggested changes to feature/actions were wrongly replacing benefit instead.

2024-10-06 11:20 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | open whatsapp or telegram from the app           | send Whatsapp or Telegram messages from within the app                                         |
Bo Chang was talking about changing the feature (I want to) instead of the benefit (So that I can)
now both are feature instead of benefit

2024-10-06 11:20 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +| `* *`    | event planner           | set list of type of vendors I need for a event   | indicate the types of vendors required for an event                                            |
same issue as line 313 (feature instead of benefit)

2024-10-06 16:02 UTC, Jasperabez reviewed
LGTM merge after Bo Chang review?

2024-10-07 12:08 UTC, C5hives approved these changes
Sorry for the delay—looks good!

2024-10-07 16:16 UTC, merged