Add use case for assign command to developer guide
AY2425S1-CS2103-F13-2/tp pull request #55
Opened 2024-10-05 15:45 UTC by kevin-pek

Resolves #36.

Add use for the `assign` command to the developer guide.

2024-10-05 19:06 UTC, Jasperabez requested changes
Few nitpicks as previously highlighted by Bo Chang @C5hives in my PR can refer back to which would be helpful I think

2024-10-05 19:06 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +2. System verifies that both the vendor and event exist.
Should be an extension instead? there's no visual change displayed to user. (This is what Bo Chang corrected for me last time)

2024-10-05 19:06 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +3. System verifies that the vendor is not already assigned to the event.
same issue

2024-10-05 19:06 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +* 3a. The vendor has already been assigned to the event.
can be bundled with number 2 extensions?

2024-10-05 19:06 UTC, Jasperabez commented on docs/DeveloperGuide.md
> +* 1a. The command entered by the user does not exist.
Bo Chang similarly raised an issue regarding the scope of this extension. It doesn't seems quite right to place it as an extension for this use case (since if command doesn't exist it does not belong to this use case at all?)

2024-10-05 19:35 UTC, kevin-pek commented on docs/DeveloperGuide.md
> +* 1a. The command entered by the user does not exist.
That is a good point, nice catch! While editing this PR, I also realised that another error case to handle is the situation when the command entered does not match the required format. Have replaced this extension with the new case in the latest commit.

2024-10-06 04:24 UTC, C5hives commented on docs/DeveloperGuide.md
> +2. System verifies that both the vendor and event exist.
Resolving as developer guide has been edited to address this.

2024-10-06 04:24 UTC, C5hives commented on docs/DeveloperGuide.md
> +3. System verifies that the vendor is not already assigned to the event.
Resolving as developer guide has been edited to address this.

2024-10-06 04:24 UTC, C5hives commented on docs/DeveloperGuide.md
> +* 3a. The vendor has already been assigned to the event.
Resolving as developer guide has been edited to address this.

2024-10-06 04:27 UTC, C5hives approved these changes
Looks good!

2024-10-06 04:35 UTC, Jasperabez approved these changes
LGTM thanks for the good work!

2024-10-06 04:36 UTC, merged