Implement UniqueEventList for parent model
AY2425S1-CS2103-F13-2/tp pull request #81
Opened 2024-10-11 14:57 UTC by C5hives

Resolves #75 

Changes:
- Add `isSameEvent` method to `Event` class
- Add `UniqueEventList` to mirror functionality of `UniqueVendorList`
- Add exceptions for handling event operations
- Modified interfaces `Model` and `ReadOnlyAddressBook`
- Update `ModelManager` and `AddressBook` to store events, as well as implement methods that operate on events (from their updated interfaces)
- Update existing `ModelStub` and `AddressBookStub` used in `AddCommandTest` and `AddressBookTest` respectively
- Add basic tests for `UniqueEventList`

The current `CreateEventCommand` is still non-functional and none of the new methods are in use yet.
Note: Only the model has been updated. The storage component has not been updated to store Events in JSON yet.

2024-10-11 16:14 UTC, Jasperabez approved these changes
LGTM, I think is fine for not full test coverage but would have to create an issue to document what test coverage should be done.

Would merge once the issue for test case is created.

2024-10-11 16:17 UTC, Jasperabez commented
yikes it seems like codecov doesn't allow the merge to pass sooo I guess have to create the tests case.

I'll work on creating the util class sometime tmr so we can up the testing and merge it in on Sunday perhaps? Unless you'll want to work on that @C5hives

2024-10-11 16:20 UTC, C5hives commented
I think @hanscau might be interested in setting up the testing part. In the meantime, I'll work on the storage issue for events.

I can up the coverage on this PR once the testing utils are set up.

2024-10-13 10:59 UTC, C5hives commented
More tests added so codecov bot gets off my case!

2024-10-13 11:05 UTC, kevin-pek commented
Want to check if this we're planning to implement the `getFilteredVendorList()` method for the `Model` class in this PR? Realise that this is a blocker for #71. If not I can introduce the changes in the issue.

2024-10-13 11:13 UTC, C5hives commented
> Hello, jumping in to check if this we're planning to implement the `getFilteredEventList()` method for the `Model` class in this PR? Realise that this is a blocker for #71. If not I can introduce the changes in the PR for the assign command issue.

Oh shucks, you're right—will add `getFilteredEventList()` in a bit. Don't merge this PR just yet.

2024-10-13 11:26 UTC, kevin-pek commented
> > Hello, jumping in to check if this we're planning to implement the `getFilteredEventList()` method for the `Model` class in this PR? Realise that this is a blocker for #71. If not I can introduce the changes in the PR for the assign command issue.
> 
> Oh shucks, you're right—will add `getFilteredEventList()` in a bit. Don't merge this PR just yet.

Thanks, much appreciated @C5hives !

2024-10-13 12:29 UTC, C5hives commented
No support for filtering with a `Predicate` yet.

I don't think it's necessary for `v1.3`, so in the spirit of iterative development, I have left it out :D

2024-10-13 15:30 UTC, Jasperabez requested changes
LGTM but have some weird html markup in one of the javadocs

2024-10-13 15:30 UTC, Jasperabez commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> + */
Is the markup tag here a glitch? `<p>

2024-10-13 16:15 UTC, C5hives commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> + */
Nope. It's intentional to separate the javadocs into distinct paragraphs.

I didn't like the massive wall of text that was the original javadoc, so I changed it.

If need be, I can revert for consistency's sake

2024-10-13 16:35 UTC, Jasperabez commented on src/main/java/seedu/address/model/event/UniqueEventList.java
> + */
hmm if that's the case let just leave it in since it's valid javadocs syntax anyways

2024-10-13 16:35 UTC, Jasperabez approved these changes

2024-10-13 16:35 UTC, merged