Reworked current delete command for vendor delete
AY2425S1-CS2103-F13-2/tp pull request #82
Opened 2024-10-12 22:24 UTC by Jasperabez

The command format is updated as per mentioned in #77
`delete v/1`

- Deleting multiple items was not implemented due to the complexity of testing
- The command is extended in such a way adding delete for events should be trivial

2024-10-12 22:47 UTC, Jasperabez commented
no idea why my codecov no passing despite adding test cases that accounts for it

2024-10-13 08:01 UTC, C5hives commented
You might want to open an issue for this PR just to follow the workflow requirements for the tP. Just admin work—the PR can remain as is.

2024-10-13 08:16 UTC, C5hives requested changes
Logic is generally ok, but some refactoring could be done to better adhere to OOP principles.

Let me know if you have any other suggestions instead.

2024-10-13 08:16 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            throw new CommandException(Messages.MESSAGE_INVALID_COMMAND_FORMAT);
This logic feels out of place and requires you to create another enum to perform checks.

You might want to consider shifting this logic to be handled by `DeleteCommandParser` instead. The parser itself already does `Prefix` checks, which you can take advantage of and forgo the enum `ItemTypeToDelete` entirely.

2024-10-13 08:16 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
The name DeleteCommand will no longer be descriptive enough once support for deleting vendors and events is added.

You might want to consider turning this class into an abstract class and use polymorphism to handle deleting vendors and events as separate classes.

2024-10-13 08:16 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +    public DeleteCommand(ItemTypeToDelete itemType, Index targetIndex) {
Passing flags around to determine class behaviour is a code smell. As mentioned, consider polymorphism instead.

2024-10-13 08:16 UTC, C5hives commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +    }
Following the subsequent comments, I would recommend getting rid of this enum entirely and rely on the existing `CliSyntax` class to perform checks.

2024-10-13 10:15 UTC, Jasperabez commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
Refactored!

2024-10-13 10:57 UTC, C5hives requested changes
Nice job on the refactoring! Just one more nitpick—the stub used in `DeleteCommandTest` could be moved to the bottom of the file to allow the test methods to come first

2024-10-13 10:57 UTC, C5hives commented on src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
>      }
You might want to put the stub at the bottom of the file and let the test methods come first.

The stub is usually not as important and placing it near the bottom of the file would help get to the meat of the class (which are the tests). Also just for standardisation across all the test classes.

2024-10-13 16:25 UTC, C5hives approved these changes
Looks good!

2024-10-13 16:26 UTC, merged