Parser implementation for unassign
AY2425S1-CS2103-F13-2/tp pull request #99
Opened 2024-10-16 08:09 UTC by Jasperabez

Copy the implementation of assign command over to unassign, create dummy functions (TODO) for those needing to access the new associations model.

Tests currently being worked on

Resovles: #85

2024-10-16 09:25 UTC, C5hives requested changes
Looks good except for some formatting changes that need to be addressed

2024-10-16 09:25 UTC, C5hives commented on src/main/java/seedu/address/model/ModelManager.java
> +    // ==================================================================================
Need to revert this change by your auto formatter.

2024-10-16 09:25 UTC, C5hives commented on src/main/java/seedu/address/model/AddressBook.java
> +     * https://docs.oracle.com/javase/tutorial/java/javaOO/initial.html
You might want to change how your auto formatter runs.

You and @hanscau will end up changing the javadocs back and forth for every created PR.

2024-10-16 10:18 UTC, kevin-pek requested changes

2024-10-16 10:18 UTC, kevin-pek commented on src/main/java/seedu/address/model/AddressBook.java
> +    }
I have just merged the PR for the assign command, so this method can now be removed!

2024-10-16 10:18 UTC, kevin-pek commented on src/main/java/seedu/address/model/Model.java
> +    boolean isVendorAssignedToEvent(Vendor vendor, Event event);
Ditto.

2024-10-17 01:51 UTC, kevin-pek approved these changes

2024-10-17 01:57 UTC, C5hives approved these changes
Looks good!

2024-10-17 02:47 UTC, merged